DROP TABLE IF EXISTS Listeners
DROP TABLE IF EXISTS Artists
DROP TABLE IF EXISTS Song
DROP TABLE IF EXISTS Album
DROP TABLE IF EXISTS PlayList
DROP TABLE IF EXISTS PlayListLikes_Listeners
DROP TABLE IF EXISTS Playlist_Song
DROP TABLE IF EXISTS Auth_ids;